version: '3.7'

networks:
    default:
        attachable: true

services:
    flask:
        image: flask:latest
        deploy:
            mode: global

    nginx:
        image: mynginx:latest
        ports:
            - 80:80
        deploy:
            mode: global
