version: '3.7'

networks:
    default:
        attachable: true

services:
    flask:
        image: flask
        deploy:
            mode: global

    nginx:
        image: nginx
        ports:
            - 80:80
        deploy:
            mode: global
