version: "3.9"

networks:
    default:
        attachable: true

services:
    flask:
        image: flask:latest
        deploy:
            mode: replicated
            replicas: 4
            placement:
                max_replicas_per_node: 2

    nginx:
        image: mynginx:latest
        ports:
            - 80:80
        deploy:
            mode: global
